## mpv shaders
# anime4k shaders
[".config/mpv/shaders"]
  type = "archive"
  url = "https://github.com/Tama47/Anime4K/releases/latest/download/GLSL_Mac_Linux_High-end.zip"
  refreshPeriod = "168h"
  include = ["shaders/**"]
  stripComponents = 1

# fsr shaders
[".config/mpv/shaders/FSR.glsl"]
  type = "file"
  url = "https://gist.githubusercontent.com/agyild/82219c545228d70c5604f865ce0b0ce5/raw/FSR.glsl"
  refreshPeriod = "168h"

## mpv scripts
# uosc, feature-rich osc/ui
[".config/mpv"]
  type = "archive"
  url = "https://github.com/tomasklaen/uosc/releases/latest/download/uosc.zip"
  refreshPeriod = "168h"
# mpris support
[".config/mpv/scripts/mpris.so"]
  type = "file"
  url = "https://github.com/hoyon/mpv-mpris/releases/latest/download/mpris.so"
  refreshPeriod = "168h"
# sponsorblock
[".config/mpv/scripts/sponsorblock_minimal.lua"]
  type = "file"
  url = "https://codeberg.org/jouni/mpv_sponsorblock_minimal/raw/master/sponsorblock_minimal.lua"
  refreshPeriod = "168h"
# ani-skip, skip anime opening and ending
[".config/mpv/scripts/ani-skip.lua"]
  type = "file"
  url = "https://raw.githubusercontent.com/synacktraa/ani-skip/master/skip.lua"
  refreshPeriod = "168h"
# autoselect non-dub audio and sub (especially for anime)
[".config/mpv/scripts/trackselect.lua"]
  type = "file"
  url = "https://raw.githubusercontent.com/po5/trackselect/refs/heads/master/trackselect.lua"
  refreshPeriod = "168h"
# videoclip
[".config/mpv/scripts/videoclip"]
  type = "git-repo"
  url = "https://github.com/Ajatt-Tools/videoclip.git"
  refreshPeriod = "168h"
# seek to a specific timestamp
[".config/mpv/scripts/seek-to.lua"]
  type = "file"
  url = "https://raw.githubusercontent.com/occivink/mpv-scripts/master/scripts/seek-to.lua"
  refreshPeriod = "168h"
# image thumbnail
[".config/mpv/scripts/thumbfast.lua"]
  type = "file"
  url = "https://raw.githubusercontent.com/po5/thumbfast/master/thumbfast.lua"
  refreshPeriod = "168h"
# audio visualizer
[".config/mpv/scripts/visualizer.lua"]
  type = "file"
  url = "https://raw.githubusercontent.com/mfcc64/mpv-scripts/master/visualizer.lua"
  refreshPeriod = "168h"
