## mpv shaders
# anime4k shaders
{{ $anime4kOs := "Windows" }}
{{ if eq .chezmoi.os "darwin" }}
  {{ $anime4kOs = "Mac_Linux" }}
{{ else if eq .chezmoi.os "linux" }}
  {{ if (.chezmoi.kernel.osrelease | lower | contains "microsoft") }}
    {{ $anime4kOs = "Windows" }}
  {{ else }}
    {{ $anime4kOs = "Mac_Linux" }}
  {{ end }}
{{ end }}
[".config/mpv/shaders"]
  type = "archive"
  url = "https://github.com/Tama47/Anime4K/releases/latest/download/GLSL_{{ $anime4kOs }}_High-end.zip"
  refreshPeriod = "168h"
  include = ["shaders/**"]
  stripComponents = 1

# fsr shaders
[".config/mpv/shaders/FSR.glsl"]
  type = "file"
  url = "https://gist.githubusercontent.com/agyild/82219c545228d70c5604f865ce0b0ce5/raw/FSR.glsl"
  refreshPeriod = "168h"

## mpv scripts
# uosc, feature-rich osc/ui
[".config/mpv"]
  type = "archive"
  url = "https://github.com/tomasklaen/uosc/releases/latest/download/uosc.zip"
  refreshPeriod = "168h"
# sponsorblock
[".config/mpv/scripts/sponsorblock_minimal.lua"]
  type = "file"
  url = "https://codeberg.org/jouni/mpv_sponsorblock_minimal/raw/master/sponsorblock_minimal.lua"
  refreshPeriod = "168h"
# ani-skip, skip anime opening and ending
[".config/mpv/scripts/ani-skip.lua"]
  type = "file"
  url = "https://raw.githubusercontent.com/synacktraa/ani-skip/master/skip.lua"
  refreshPeriod = "168h"
# manage bookmarks
[".config/mpv/scripts/bookmarker-menu.lua"]
  type = "file"
  url = "https://raw.githubusercontent.com/NurioHin/mpv-bookmarker/master/bookmarker-menu.lua"
  refreshPeriod = "168h"
# image crop
[".config/mpv/scripts/crop.lua"]
  type = "file"
  url = "https://github.com/TheAMM/mpv_crop_script/releases/latest/download/mpv_crop_script.lua"
# videoclip
[".config/mpv/scripts/videoclip"]
  type = "git-repo"
  url = "https://github.com/Ajatt-Tools/videoclip.git"
  refreshPeriod = "168h"
# seek to a specific timestamp
[".config/mpv/scripts/seek-to.lua"]
  type = "file"
  url = "https://raw.githubusercontent.com/occivink/mpv-scripts/master/scripts/seek-to.lua"
  refreshPeriod = "168h"
# image thumbnail
[".config/mpv/scripts/thumbfast.lua"]
  type = "file"
  url = "https://raw.githubusercontent.com/po5/thumbfast/master/thumbfast.lua"
  refreshPeriod = "168h"
# audio visualizer
[".config/mpv/scripts/visualizer.lua"]
  type = "file"
  url = "https://raw.githubusercontent.com/mfcc64/mpv-scripts/master/visualizer.lua"
  refreshPeriod = "168h"
