# set video resolution to auto
video_width=-2
video_height=-2

# audio format
audio_format=opus
audio_bitrate=128k

# filename template
video_folder_path=~/media/clip
filename_template=clip_%Y%M%D_%H%N%S

