# git status on file
[plugin]
prepend_fetchers = [
  { id = "git", name = "*", run = "git"},
  { id = "git", name = "*/", run = "git" }
]

prepend_previewers = [
  { mime = "audio/*", run = "exifaudio" }
]
