# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory $fill $status $all$character
"""

[fill]
symbol = " "

[status]
style = "bold red"
format = "[$status]($style)"
disabled = false
